#!/usr/bin/env python3
"""Generate a docker-compose.yml sized to the machine it runs on.

The cpuset strings in a compose file are literals -- compose cannot compute
them -- and a `cpuset: "3"` on a two-core server fails to start the container.
So the layout is generated per host instead of copied between them.

Only the standard library is imported: this runs on a bare server before the
project's dependencies exist.

    python3 scripts/gen_compose.py                  # preset-sized, one node
    python3 scripts/gen_compose.py -n 4 --preset medium
    python3 scripts/gen_compose.py -n 4 --cores 1 --ram 1

`--preset` mirrors src/node/gui/presets.py: small is a quarter of the machine,
medium a half capped at 4 GiB, large everything but one core capped at 16 GiB.
The preset describes *one* node's share, so `-n 4 --preset medium` deliberately
oversubscribes; `--cores/--ram` state a budget outright.
"""

from __future__ import annotations

import argparse
import os
import sys

# Kept in step with node.gui.presets._SHARES and node.agent.config.MIN_RAM_GB.
SHARES = {
    "small": (0.25, 0.25, 2.0),
    "medium": (0.50, 0.50, 4.0),
    "large": (None, 0.75, 16.0),
}
HEADROOM_GB = 1.0
MIN_RAM_GB = 0.5


def total_ram_gb() -> float:
    with open("/proc/meminfo") as handle:
        for line in handle:
            if line.startswith("MemTotal:"):
                return int(line.split()[1]) / 1024**2
    raise RuntimeError("MemTotal missing from /proc/meminfo")


def preset_budget(level: str, cores: int, ram_gb: float) -> tuple[int, float]:
    core_share, ram_share, ceiling = SHARES[level]
    n = max(1, cores - 1) if core_share is None else max(1, int(cores * core_share))
    ram = min(ram_gb * ram_share, ceiling)
    ram = min(ram, max(MIN_RAM_GB, ram_gb - HEADROOM_GB))
    return min(n, cores), round(max(ram, MIN_RAM_GB), 1)


def cpusets(count: int, per_node: int, total: int) -> list[str]:
    """One contiguous block per node, wrapping only if the cores run out."""
    out = []
    for i in range(count):
        ids = [(i * per_node + k) % total for k in range(per_node)]
        out.append(compress(sorted(set(ids))))
    return out


def compress(ids: list[int]) -> str:
    """[0,1,2,5] -> "0-2,5" -- the form docker expects."""
    parts, start, prev = [], ids[0], ids[0]
    for cid in ids[1:] + [None]:
        if cid == prev + 1:
            prev = cid
            continue
        parts.append(str(start) if start == prev else f"{start}-{prev}")
        if cid is None:
            break
        start = prev = cid
    return ",".join(parts)


def render(count: int, cores: int, ram: float, sets: list[str], note: str) -> str:
    ram_str = f"{ram:g}"
    head = f"""\
# GENERATED by scripts/gen_compose.py -- do not hand-edit; regenerate per host.
#
# {note}
#
# The budget is passed explicitly because psutil inside a container reads the
# *host* /proc: left to auto-detect, the agent would claim the whole box.
# cpuset gives each node its own cores -- pick_core_ids() starts from the
# affinity mask it is allowed to use, so without it every node would crowd
# onto cores 0..N-1 and leave the rest of the machine idle.

x-node: &node
  build:
    context: .
    dockerfile: docker/Dockerfile
  image: sarajevo-node:latest
  restart: unless-stopped
  environment: &node-env
    # Empty falls through to DEFAULT_SERVER in src/node/agent/config.py.
    NODE_AGENT_SERVER: "${{NODE_SERVER:-}}"
    NODE_AGENT_LOG_LEVEL: "${{NODE_LOG_LEVEL:-info}}"
    NODE_AGENT_CORES: "{cores}"
    NODE_AGENT_RAM_GB: "{ram_str}"
    NODE_AGENT_STATE_DIR: /var/lib/node-agent
  # The agent caps its own training child at 80% of the budget; this is the
  # outer fence for the rest of the container.
  mem_limit: {ram_str}g
  command: ["run"]

services:
"""
    body = ""
    for i in range(1, count + 1):
        body += f"""\
  node-{i}:
    <<: *node
    container_name: node-{i}
    hostname: node-{i}
    cpuset: "{sets[i - 1]}"
    environment:
      <<: *node-env
      NODE_AGENT_NAME: node-{i:02d}
    volumes:
      - node{i}-state:/var/lib/node-agent

"""
    vols = "volumes:\n" + "".join(f"  node{i}-state:\n" for i in range(1, count + 1))
    return head + body + vols


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("-n", "--nodes", type=int, default=1, help="how many containers")
    ap.add_argument("--preset", choices=sorted(SHARES), help="size each node by preset")
    ap.add_argument("--cores", type=int, help="cores per node (overrides --preset)")
    ap.add_argument("--ram", type=float, help="GiB per node (overrides --preset)")
    ap.add_argument("-o", "--out", default="docker-compose.yml")
    args = ap.parse_args()

    hw_cores = os.cpu_count() or 1
    hw_ram = total_ram_gb()

    if args.cores and args.ram:
        cores, ram = args.cores, args.ram
        note = f"{args.nodes} node(s), {cores} core / {ram:g} GiB each (explicit budget)."
    else:
        level = args.preset or "medium"
        cores, ram = preset_budget(level, hw_cores, hw_ram)
        if args.cores:
            cores = args.cores
        if args.ram:
            ram = args.ram
        note = f"{args.nodes} node(s) on the '{level}' preset: {cores} core / {ram:g} GiB each."

    print(f"host: {hw_cores} cores, {hw_ram:.2f} GiB", file=sys.stderr)
    print(f"plan: {args.nodes} x ({cores} cores, {ram:g} GiB)", file=sys.stderr)

    demand = args.nodes * cores
    if demand > hw_cores:
        print(
            f"warning: {demand} cores requested, host has {hw_cores}"
            f" -- cpusets overlap, {demand / hw_cores:.1f}x oversubscribed",
            file=sys.stderr,
        )
    if args.nodes * ram > hw_ram:
        print(
            f"warning: {args.nodes * ram:g} GiB of limits on a {hw_ram:.1f} GiB host"
            " -- containers may be OOM-killed under load",
            file=sys.stderr,
        )

    with open(args.out, "w") as handle:
        handle.write(render(args.nodes, cores, ram, cpusets(args.nodes, cores, hw_cores), note))
    print(f"wrote {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
